### ISSUE TITLE
Specto Not Working on Kodi v17

### ISSUE THREAD

**Issue by rj452** [mrknow/filmkodi#405]
Specto wont install. It always says"Failed to install  Dependency". Please Fix.

Thanks ^_^

**Comment by xxcriticxx** [comment]
install URLResolver

**Comment by rgw1955** [comment]
When trying to install updates, says "dependencies not met"  will not install.  Issues with no streams being available??

**Comment by crash180** [comment]
I tried to install URLresolver, but it said it stated it is already installed.

**Comment by xxcriticxx** [comment]
kodi log please

**Comment by mrknow** [comment]
try new version 2016.08.28.1

**Comment by rgw1955** [comment]
What is the url to install "Specto"?

Date: Sun, 28 Aug 2016 12:31:33 -0700

**Comment by BankruptEd** [comment]
http://filmkodi.com/repository

**Comment by BankruptEd** [comment]
Try using this YouTube video

https://youtu.be/LWRYJnb8EMI

**Comment by rgw1955** [comment]
getting a message "Add-on is incompatible or has been marked broken in repository. Dependencies not met. lease contact Add-on author."  Now what?
Date: Sun, 28 Aug 2016 13:15:56 -0700

**Comment by BankruptEd** [comment]
Sorry brother, that's out of my range. Hopefully someone else weighs in.

**Comment by BankruptEd** [comment]
You probably don't wanna hear this, but openload still showing me pigeons.
I've received all the updates as far as I know. Just an FYI.

**Comment by BankruptEd** [comment]
As far as I know I have never updated my Specto. I get updates coming
through all the time for the version I have, so I guess my question is - Do
I NEED to update Specto? Will I stop receiving updates if I don't? Because
in all honesty I would prefer to leave it be. Seems like lots of people are
having issues with the newer versions. So am I ok or do I HAVE to update
eventually?
