### ISSUE TITLE
Specto favourites are gone

### ISSUE THREAD

**Issue by Zalinas** [mrknow/filmkodi#492]
Hi, since the last update 2016.09.17.2 all the tv shows that i put in favourites are gone. When i try to search the tv shows not all off them are found... i can find Narcos but the blacklist, hawaii five 0 and Zoo for example are not found.
What is wrong?

**Comment by BankruptEd** [comment]
You have a couple choices at this time.

1 - Uninstall the filmkodi repository then go to the link below and get
specto plugin
2016.09.01.1 install this and all you favorites will come back. Hopefully a
new update
may fix the problem. wait for few days and install the repository.
http://kodi.filmkodi.com/plugin.video.specto/

2 - Add all your favorites all over again. You will first have to remove an
item from favorites and then add it again as all your shows are still
technically in your favorites, they just don't show up.

On Sep 19, 2016 3:48 AM, "Zalinas" <notifications@github.com> wrote:

Hi, since the last update 2016.09.17.2 all the tv shows that i put in
favourites are gone. When i try to search the tv shows not all off them are
found... i can find Narcos but the blacklist, hawaii five 0 and Zoo for
example are not found.
What is wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/492>, or mute the thread

**Comment by BankruptEd** [comment]
If you choose #1, this means you need to turn off auto-update as this fix
just rolls you back to an earlier update and any new update applied will
wipe it. It's unclear when or if there will be an official fix from Mr.
Know.

**Comment by BankruptEd** [comment]
Should also add that fix #1 is courtesy of user mageorge. This topic was
already gone over in a previous post where mageorge came through with it.

**Comment by Zalinas** [comment]
BakruptEd thnx for your reply.
I will try this today and let you know if it works.

**Comment by BankruptEd** [comment]
If u do it correctly it will work. It's been proven many times over
already. What I don't like is you can't get any future updates until an
official fix comes through. I've decided to go the tedious way and simply
reenter my favorites. I just hope  I don't have to do this regularly. I had
lots of fav's. Big hassle even remembering half of them.

**Comment by Zalinas** [comment]
It works!  Too bad that we have to waut now for an officialfix.  But thnx for the help!

**Comment by BankruptEd** [comment]
No worries. Just trying to pay back the help I've received. Peace

**Comment by mrknow** [comment]
update add-on. And manualy re create favorites
