### ISSUE TITLE
Openload Suddenly Wants Pairing

### ISSUE THREAD

**Issue by buddyjack2** [mrknow/filmkodi#573]
For just the past couple of days (end of Oct. 2016), nearly every source I choose for TV shows in Specto now produces Openload's authorization warning, asking me to go to its website and pair devices in order to get 4 hours' worth of viewing. This seems to occur whether or not I choose sources that mention Openload or not. What's happened in just the past few days to cause that? Any fixes?

**Comment by BankruptEd** [comment]
The only ones that ask so far as I know (with more to come I'm sure) is
*Openload" and "Thevideo" what a pain the ass. Better than them asking for
money though I suppose.

On Nov 2, 2016 10:04 PM, "buddyjack2" <notifications@github.com> wrote:

For just the past couple of days (end of Oct. 2016), nearly every source I
choose for TV shows in Specto now produces Openload's authorization
warning, asking me to go to its website and pair devices in order to get 4
hours' worth of viewing. This seems to occur whether or not I choose
sources that mention Openload or not. What's happened in just the past few
days to cause that? Any fixes?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/573>, or mute the thread

**Comment by mrknow** [comment]
Here you have a link to the new beta version script.mrknow.urlresolver http://kodi.filmkodi.com/beta/script.mrknow.urlresolver/script.mrknow.urlresolver-2016.11.4.1.zip

remember that this is a beta version. if it does not work, go back to the previous

**Comment by buddyjack2** [comment]
Thanks so much! I'll try installing it tonight.

**Comment by dracosc** [comment]
He fixed it already!!!! He is the man!!!!

**Comment by dracosc** [comment]
Are you going to continue the official Mrknow.Urlresolver with pairing, ang give to your "Openload fans" a beta? :-)

**Comment by mrknow** [comment]
@dracosc - maybe it's a good idea. For now, I have no idea.
