### ISSUE TITLE
no auto "mark as watched" for Trakt in Specto

### ISSUE THREAD

**Issue by PapaPow** [mrknow/filmkodi#574]
Based on my observation, I've noticed that after watching a few TV episodes and movies that Specto does not automatically mark viewings as watched.  Is there a way viewings can be marked automatically rather then manually?  I have separately installed the Trakt Manager addon for Kodi to allow synchronization for both watched TV episodes and movies.

Thanks in advance for any provided feedback.

**Comment by BankruptEd** [comment]
I find it always marks things watched if you let it play right to the very
end, but often won't if you stop it a bit early.

**Comment by PapaPow** [comment]
You're absolutely correct and I have let all streams play to the very end, yet I'm still running into this dilemma for all my viewings (hence why I've placed a post).

Thanks in advance for any further provided feedback.

**Comment by BankruptEd** [comment]
I see. Good luck. Hopefully someone has a fix.

**Comment by mrknow** [comment]
Now Specto making shows as watched after watching  90% of  video time. 
I will change this to  80% in next add-on update

**Comment by mrknow** [comment]
Fixed

**Comment by giventofly** [comment]
kind of a gravedigger, but this is happening to me and i lwait till the end of stream

**Comment by 71Baker** [comment]
Happening for me too. If I then go to trakt.tv and mark it, then check my trakt progress it is ok.

**Comment by BankruptEd** [comment]
Hi Baker. I was wondering if you could explain to me just what trakt does
for a person? Everyone seems to love it, but I just don't understand what
it does, or what it's for. I installed it on Specto,and I just don't get
it. I see that you can save things to a favorites folder, but Specto
already has that. Is it because you can have it with multiple add-ons while
saving everything to a single trakt favorites folder? Any help much
appreciated

**Comment by HacktionMan** [comment]
Trakt is great. You can make multiple things with it. 
Here is my scenario: I love movies and follow a few TV shows. 

Every time i watch something, be it in my kodi, friends house, cinema, tv, etc, I mark it watched on my trakt account. I have the kodi official trakt addon that marks automatically what i watch in all my kodi's around the house. And when i have to add something manually I use my android phone with the app Movie Mate that allows me to find movies and add them as watched (or add them to the watchlist, more on that later)
I need this for two reasons:
- Every movie i watched is marked watched in all my kodi's (phone, living room, bedroom, etc) and I activate "Hide watched" option so, I only have posters for movies that I have not seen. If i make a full reset to kodi, i just install trakt addon and all the content is marked as watched and can be hided. 
- trakt knows what I watch so, my recommended movies in trakt is made only of movies that I have not seen related to my tastes. I use a modded skin that allows me to have that recommend movies playlist as a widget and have it on my kodi main screen with different new movies. I can also use trakt playlists made by me, but I don't, Instead I follow playlisters that make lists like Marvel Cinematic Universe, Top 10 Samurai Movies, Quentin Tarantino favorite movies, etc, etc, etc, etc

Second best thing: I use the watchlist. It is a special playlist suited for you to remember what you want to watch in the future. I moved from imdb watchlist to trakt because when I mark or watch something on kodi, it is removed from trakt watchlist. I also import the watchlist to my kodi library so my library is made only of movies I plan to see and when I see them, they are removed from trakt watchlist and sync across all my kodi devices. 
I can also add a movie to the watchlist on my phone, or website at work, and when I arrive home, all my kodi's will have that movie in the "Latest added movies"

For TV shows, I use the collection feature of trakt, because when you add a show, it will auto update with new episodes when they are broadcasted. If you import the collection to TV show library in kodi, it will show you on "Recently added episoded" new episodes on the same day they are broadcasted. Also, episodes you watch are marked, so on every kodi, the "In progress TV shows" section is the same.

I add things to my trakt, trakt recommends me stuff I like, I follow other users and friends and all those moveis are in the library, widgets and smart playlists like "action movies in library made after 2000 with minimum 7/10 on imdb" (I hide watched, so everything that you see is unwatched)

Specto is the player but all the selected content is comes from trakt fully synced and automated.

**Comment by HacktionMan** [comment]
By the way, people that are having troubles with Marked as Watched: 
If im not mistaken Specto just tells Kodi that it is watched and Trakt addon reports it to the website and It is not instant: check your settings for Trakt addon from official repository,

**Comment by BankruptEd** [comment]
Ok then. That's perfect. I think I have a decent understanding of trakt
now. Thanks for taking the time to reply, and with great detail. Much
appreciated Hacktion 😉. Peace.

**Comment by ellisw01** [comment]
I am having the same issue the Specto on Kodi 17.3 not marking as watched.
I have just moved over to Specto from Exodus with TrakT installed & worked fine with Exodus on Kodi 17.3 but with the problems I intalled Specto & synced the TrakT account everything came over but even leaving a stream to run to 100% & it returning to the menu it's not marking them as watched, I have cleared cache & even restarted Kodi & the box with the same outcome.
I am also having an issue with the move search not showing the Fan Art!
