### ISSUE TITLE
Specto disappeared from Kodi and when I re-install it, the install fails? Thanks

### ISSUE THREAD

**Issue by wyattspoppa** [mrknow/filmkodi#831]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: _____
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: _____
---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by wyattspoppa** [comment]
Specto disappeared from Kodi, when I reinstall, it fails after 0%

**Comment by BankruptEd** [comment]
Did it disappear after an update came through while u were in Specto?

On Apr 4, 2017 10:54 PM, "wyattspoppa" <notifications@github.com> wrote:

Specto disappeared from Kodi, when I reinstall, it fails after 0%

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/831#issuecomment-291730103>, or mute
the thread

**Comment by mrknow** [comment]
Try install from zip (howto - http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files) this  files: 
http://kodi.filmkodi.com/script.mrknow.urlresolver/script.mrknow.urlresolver-2017.04.04.3.zip
http://kodi.filmkodi.com/script.specto.media/script.specto.media-2016.07.07.zip
http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2017.04.04.3.zip

**Comment by BankruptEd** [comment]
MrKnow, I just wanted to point out that almost all the issues I've had (and
presumably the same for others) have been caused by an update coming
through while one is currently in Specto. Updates don't seem to like it
when your messing around in the add-on at the time they come through.

Could there not be an easy fix to this? Like make updates only apply
themselves when the add-on is not active? Or perhaps a notification that
there is an update so that you can shut down Specto first, so that they can
update safely? Or maybe you have other ideas that could fix this?

Every time an update comes through, I have to wonder did it screw something
up this time? And if it did, am I gonna be able to fix it? It makes
computer noobs like myself live in fear of when the next update's gonna
screw me up. I have to believe their is a better way to apply updates when
it's obvious they have the potential to disable your add-on if you are
currently using it.

**Comment by Palidino** [comment]
I'd like to chime in here and say that I don't turn on box off as often as I should (I use my TV's netflix app so Specto is more often than not pulled up behind the netflix tv app doing it's own thing), and in the last 2-3 days I assume there have been 2 updates for Specto. This is because every time there is an update and Specto is open, Kodi deletes Specto/fails to install and I have to go re-install it.

**Comment by BankruptEd** [comment]
Thank you. That's what I've been saying. I wonder if we are not better to
keep auto update off? I've had this happen at least a few times but also
had a variety of other issues as a result of being in Specto when an update
comes through.
